# Generated by Django 2.2.5 on 2020-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riddle',
            old_name='riddle_text',
            new_name='riddle_text1',
        ),
        migrations.AddField(
            model_name='riddle',
            name='riddle_text2',
            field=models.TextField(default='people'),
        ),
    ]
